name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      email:
        description: "Email to login"
        type: environment
        required: true
      pass:
        description: "Pass to login"
        type: environment
        required: true
      url:
        description: "URL of carousel to upload"
        type: environment
        required: true
      altOfFile:
        description: "Alternative text of carousel"
        type: environment
        required: true
      postText:
        description: "Text of the post"
        type: environment
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
